[2022-11-30T20:17:29.789+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag.print_len_csv manual__2022-11-30T20:17:24.824286+00:00 [queued]>
[2022-11-30T20:17:29.802+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: first_dag.print_len_csv manual__2022-11-30T20:17:24.824286+00:00 [queued]>
[2022-11-30T20:17:29.802+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T20:17:29.803+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-30T20:17:29.803+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-30T20:17:29.819+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): print_len_csv> on 2022-11-30 20:17:24.824286+00:00
[2022-11-30T20:17:29.825+0000] {standard_task_runner.py:55} INFO - Started process 11323 to run task
[2022-11-30T20:17:29.828+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'print_len_csv', 'manual__2022-11-30T20:17:24.824286+00:00', '--job-id', '787', '--raw', '--subdir', 'DAGS_FOLDER/***1t.py', '--cfg-path', '/tmp/tmpyr_2ypas']
[2022-11-30T20:17:29.830+0000] {standard_task_runner.py:83} INFO - Job 787: Subtask print_len_csv
[2022-11-30T20:17:29.901+0000] {task_command.py:376} INFO - Running <TaskInstance: first_dag.print_len_csv manual__2022-11-30T20:17:24.824286+00:00 [running]> on host debdf09646d4
[2022-11-30T20:17:29.975+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=print_len_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T20:17:24.824286+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T20:17:24.824286+00:00
[2022-11-30T20:17:29.977+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-11-30T20:17:29.978+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'len_csv_file']
[2022-11-30T20:17:29.986+0000] {subprocess.py:86} INFO - Output:
[2022-11-30T20:17:29.988+0000] {subprocess.py:93} INFO - /bin/bash: line 1: len_csv_file: command not found
[2022-11-30T20:17:29.988+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-11-30T20:17:29.998+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-11-30T20:17:30.002+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=first_dag, task_id=print_len_csv, execution_date=20221130T201724, start_date=20221130T201729, end_date=20221130T201730
[2022-11-30T20:17:30.020+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 787 for task print_len_csv (Bash command failed. The command returned a non-zero exit code 127.; 11323)
[2022-11-30T20:17:30.040+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-30T20:17:30.066+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
